apiVersion: v1
kind: Service
metadata:
  name: {{ include "imgrsvc.fullname" . }}
  labels:
    {{- include "imgrsvc.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      nodePort: 9090
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    {{- include "imgrsvc.selectorLabels" . | nindent 4 }}
